name: Preview Deploy2

on:
  workflow_run:
    workflows: ['E2E Test PR']
    types:
      - completed

jobs:
  comment:
    name: Comment User Tip
    runs-on: ubuntu-latest
    steps:
      - name: Download user-tip.txt
        uses: actions/download-artifact@v4
        with:
          name: user-tip
          path: user-tip.txt

      - id: txtToOutput
        run: |
          if [ -f user-tip.txt ]; then
            cat user-tip.txt | xargs -I {} echo text={} >> "$GITHUB_OUTPUT"
          fi
      - uses: thollander/actions-comment-pull-request@v2
        if: ${{ steps.txtToOutput.outputs.text }}
        with:
          message: |
            ${{ steps.txtToOutput.outputs.text }}
          comment_tag: e2e-tip
